In [3]:
import pandas as pd
import numpy as np

In [4]:
# from google.colab import drive
# drive.mount("/content/drive")

In [6]:
df = pd.read_csv("/content/drive/MyDrive/multi/pima-indians-diabetes.csv", skiprows = 9, header = None)
df

0    1   2   3    4     5      6   7  8
0     6  148  72  35    0  33.6  0.627  50  1
1     1   85  66  29    0  26.6  0.351  31  0
2     8  183  64   0    0  23.3  0.672  32  1
3     1   89  66  23   94  28.1  0.167  21  0
4     0  137  40  35  168  43.1  2.288  33  1
..   ..  ...  ..  ..  ...   ...    ...  .. ..
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

[768 rows x 9 columns]

In [7]:
# 1. Number of times pregnant
# 2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
# 3. Diastolic blood pressure (mm Hg)
# 4. Triceps skin fold thickness (mm)
# 5. 2-Hour serum insulin (mu U/ml)
# 6. Body mass index (weight in kg/(height in m)^2)
# 7. Diabetes pedigree function
# 8. Age (years)
# 9. Class variable (0 or 1)
df.columns = ['P',"G","BP","S","I","BMI","D","Age","Class"]
df.head()

P    G  BP   S    I   BMI      D  Age  Class
0  6  148  72  35    0  33.6  0.627   50      1
1  1   85  66  29    0  26.6  0.351   31      0
2  8  183  64   0    0  23.3  0.672   32      1
3  1   89  66  23   94  28.1  0.167   21      0
4  0  137  40  35  168  43.1  2.288   33      1

In [8]:
# 결측치 확인
df.isna().sum()

P        0
G        0
BP       0
S        0
I        0
BMI      0
D        0
Age      0
Class    0
dtype: int64

In [13]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values


In [14]:
X.shape, y.shape

((768, 8), (768,))

- Train/ Test dataset으로 분리

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, stratify = y, test_size = 0.2, random_state = 2022
)

In [ ]:
np.unique(X_train, return_counts = True)

In [18]:
np.unique(y_test, return_counts = True)


(array([0, 1]), array([100,  54]))

- DecisionTreeClassifier


In [21]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state = 2022)
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': 2022,
 'splitter': 'best'}

In [24]:
params = {"max_depth":[2,3,4,5,6],
          "min_samples_split":[2,3,4]}

In [ ]:
from sklearn.model_selection import GridSearchCV

grid_dt = GridSearchCV(dtc, params, scoring="accuracy", cv = 5)
grid_dt.fit(X_train, y_train)

In [26]:
grid_dt.best_params_

{'max_depth': 5, 'min_samples_split': 3}

In [30]:
best_dt = grid_dt.best_estimator_
best_dt.score(X_test, y_test)

0.6558441558441559

- 실제 적용

In [31]:
X_test[0], y_test[0]

(array([  0.   , 135.   ,  94.   ,  46.   , 145.   ,  40.6  ,   0.284,
         26.   ]), 0)

In [46]:
# 차원이 달라서 오류가 난다
best_dt.predict(X_test[0])

In [35]:
print(X_test[0].shape)
print(X_test.shape)

(8,)
(154, 8)


In [45]:
pred = best_dt.predict(X_test[0].reshape(1,-1))
print("양성" if pred[0] == 1 else "음성")

음성


array([0])